#!/bin/env bash

menuList=("q) Quit" "n) Notes" "t) TODOs")

## Layout ##
main_layout() {
  TITLE=$(gum style --padding "1 8" --border double --border-foreground 255 "MySH")
  PANEL1=$(gum style --padding "1 8" --border double --border-foreground 255 "$(ls "$HOME"/myworld/notes)")
  PANEL2=$(gum style --padding "1 8" --border double --border-foreground 255 "$(cat "$HOME"/myworld/todo.txt)")
  MENU=$(gum style --padding "1 8" --border double --border-foreground 255 "$(echo "${menuList[*]}")")

  PANELS=$(gum join --horizontal "$PANEL1" "$PANEL2")

  gum join --align center --vertical "$TITLE" "$PANELS" "$MENU"
}
####

## QUIT FUNCTION ##
quit_program() {
  echo "Quitting MySH...Goodbye"
  sleep 1
  exit
}
####

## NOTES ##
note_view() {
  local menuList=("n) New" "e) Edit" "b) Back" "q) Quit")
  main_layout
  new_note() {
    read -rp "Name your note : " NOTE_NAME
    $EDITOR "notes/$NOTE_NAME"
  }
  read -rp "Enter Choice : " NOTE_CHOICE
  case "$NOTE_CHOICE" in
    q) quit_program
    ;;
    n) new_note
    ;;
    e)
      cd notes/ || exit
      clear
      gum filter | xargs "$EDITOR"
    ;;
    b) 
      NOTE_VIEW=false
    ;;
    *) echo default
    ;;
  esac
}
####

## Directory Check ##
dir_check() {
  CWD="$HOME/myworld"

  if [[ -d "$CWD" ]]; then
    echo "Way to go"
    echo "All directories are here"
    cd "$CWD" || exit
  else
    cd "$HOME || exit" || exit
    mkdir "$CWD"
    mkdir -p "$CWD"/notes
    touch "$HOME"/myworld/todo.txt
    echo "Directories Made!"
  fi
}
####

## TODO List ##
todo_do() {
  clear
  gum write --placeholder "Write TODOs and press CTRL-d to save" >> "$HOME"/myworld/todo.txt
}
####

## PROMPT ##
prompt() {
  read -rp "Enter choice : " CHOICE
    case "$CHOICE" in
      q)
        quit_program
      ;;
      n) 
        clear
        NOTE_VIEW=true
        while [[ $NOTE_VIEW = true ]]; do
          note_view
          clear
          if [ $NOTE_VIEW = false ]
          then
            break
          fi
        done
      ;;
      t)
        todo_do
      ;;
      *) echo "Try Again"
      ;;
    esac
}
####

## MAIN LOOP ##
main() {
  # Check for main directories & cd into them
  dir_check

  while :
  do
    # Layout
    main_layout
    # Prompt for main menu
    prompt
    clear
  done
}
####
main

