#!/bin/env bash

menuList=("q) Quit" "n) Notes" "t) TODOs")

## Directory Check ##
dir_check() {
  CWD="$HOME/myworld"

  if [[ -d "$CWD" ]]; then
    echo "Way to go"
    echo "All directories are here"
    cd $CWD
  else
    cd $HOME
    mkdir $CWD
    mkdir -p $CWD/notes
    touch $HOME/myworld/todo.txt
    echo "Directories Made!"
  fi
}
####

## TODO List ##
todo_do() {
  gum write --placeholder "Write TODOs on seperate line and press CTRL-d to save" >> $HOME/myworld/todo.txt
}
####

## QUIT FUNCTION ##
quit_program() {
  echo "Quitting MySH...Goodbye"
  sleep 1
  exit
}
####

## PROMPT ##
prompt() {
  read -p "Enter choice : " CHOICE
    case "$CHOICE" in
      q)
        quit_program
      ;;
      n) 
        echo "Notes"
      ;;
      t)
        todo_do
      ;;
      *) echo default
      ;;
    esac
}
####

main() {
  # Check for main directories & cd into them
  dir_check

  while :
  do
    ## Layout ##
    TITLE=$(gum style --padding "1 8" --border double --border-foreground 255 "MySH")
    PANEL1=$(gum style --padding "1 8" --border double --border-foreground 255 "$(ls $HOME/myworld/notes)")
    PANEL2=$(gum style --padding "1 8" --border double --border-foreground 255 "$(cat $HOME/myworld/todo.txt)")
    MENU=$(gum style --padding "1 8" --border double --border-foreground 255 "$(echo "${menuList[*]}")")

    PANELS=$(gum join --horizontal "$PANEL1" "$PANEL2")

    gum join --align center --vertical "$TITLE" "$PANELS" "$MENU"
    ####

    # Prompt for main menu
    prompt
  done
}

main
